name: build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: s4u/setup-maven-action@v1.18.0
        with:
          java-version: '17'
          java-distribution: 'temurin'
      - name: maven verify
        run: mvn -B verify
      - name: publish unit tests
        uses: mikepenz/action-junit-report@v5
        with:
          annotate_only: true
          check_name: Unit tests
          report_paths: '**/target/surefire-reports/TEST-*.xml'
      - name: publish integration tests
        uses: mikepenz/action-junit-report@v5
        with:
          annotate_only: true
          check_name: Integration tests
          report_paths: '**/target/failsafe-reports/TEST-*.xml'