name: build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: s4u/setup-maven-action@v1.18.0
        with:
          java-version: '17'
          java-distribution: 'temurin'
      - name: Maven verify
        run: mvn -B verify